/* =========================================================
   Amábilis & Espinosa — Datos del sitio
   Edita este archivo para actualizar contacto, propiedades y blog.
   ========================================================= */

const SITE = {
  name: "Amábilis & Espinosa",
  tagline: "Real Estate",
  // TODO: reemplazar con los datos reales del cliente
  phone: "+52 729 498 5689",
  whatsapp: "527294985689", // solo dígitos, con lada de país
  email: "contacto@amabilisespinosa.com",
  address: "Metepec, Estado de México",
  hours: "Lun – Sáb · 9:00 a 19:00",
  instagram: "https://www.instagram.com/",
  facebook: "https://www.facebook.com/",
  tiktok: "https://www.tiktok.com/",
};

const U = (id, w = 1600) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

// Acepta fotos reales del proyecto ("img/...") o ids de Unsplash de relleno
const imgSrc = (v, w = 1600) => (v.includes("/") ? v : U(v, w));

const IMG = {
  modern1: "1600596542815-ffad4c1539a9",
  modern2: "1600585154340-be6161a56a0c",
  modern3: "1600047509807-ba8f99d2cdde",
  villa: "1613490493576-7fde63acd811",
  luxury: "1512917774080-9991f1c4c750",
  house1: "1564013799919-ab600027ffc6",
  house2: "1570129477492-45c003edd2be",
  house3: "1580587771525-78b9dba3b914",
  house4: "1605276374104-dee2a0ed3cd6",
  house5: "1568605114967-8130f3a36994",
  house6: "1523217582562-09d0def993a6",
  living1: "1600210492486-724fe5c67fb0",
  living2: "1493809842364-78817add7ffb",
  interior1: "1600607687939-ce8a6c25118c",
  interior2: "1600566753190-17f0baa2a6c3",
  kitchen1: "1600573472550-8090b5e0745e",
  kitchen2: "1484154218962-a197022b5858",
  apt1: "1502672260266-1c1ef2d93688",
  apt2: "1560448204-e02f11c3d0e2",
  apt3: "1522708323590-d24dbb6b0267",
  land: "1500382017468-9049fed747ef",
  office: "1486406146926-c627a92ad1ab",
  keys: "1560518883-ce09059eeffa",
  sign: "1450101499163-c8848c66ca85",
  meeting: "1556761175-5973dc0f32e7",
  forsale: "1582407947304-fd86f028f716",
};

const PROPERTIES = [
  {
    id: "residencial-grafito-i",
    title: "Residencial Grafito I",
    zone: "Metepec",
    location: "Metepec, Estado de México",
    type: "Casa",
    operation: "Venta",
    price: 4850000,
    beds: 3, baths: 3.5, parking: 2, built: 240, land: 180,
    featured: true,
    tag: "Nuevo",
    summary: "Arquitectura contemporánea en uno de los desarrollos más buscados de Metepec.",
    description: "Casa de tres niveles con dobles alturas, cocina integral con isla, roof garden privado y acabados en madera y piedra natural. Ubicada dentro de un residencial con vigilancia 24/7, a minutos de Galerías Metepec y las principales vialidades.",
    amenities: ["Roof garden", "Vigilancia 24/7", "Cocina con isla", "Doble altura", "Cuarto de servicio", "Jardín privado"],
    images: [
      "img/propiedades/residencial-grafito-i/01.avif",
      "img/propiedades/residencial-grafito-i/02.avif",
      "img/propiedades/residencial-grafito-i/03.avif",
      "img/propiedades/residencial-grafito-i/04.avif",
      "img/propiedades/residencial-grafito-i/05.avif",
      "img/propiedades/residencial-grafito-i/06.avif",
      "img/propiedades/residencial-grafito-i/07.avif",
      "img/propiedades/residencial-grafito-i/08.avif",
      "img/propiedades/residencial-grafito-i/09.avif",
      "img/propiedades/residencial-grafito-i/10.avif",
      "img/propiedades/residencial-grafito-i/11.avif",
      "img/propiedades/residencial-grafito-i/12.avif",
      "img/propiedades/residencial-grafito-i/13.avif",
    ],
    alts: [
      "Fachada de Residencial Grafito I en Metepec, con jardín frontal y acceso privado",
      "Sala con pantalla, ventanal al jardín y doble altura",
      "Sala y comedor integrados con escalera de acceso a la planta alta",
      "Comedor con ventanal hacia el jardín",
      "Cocina integral con isla, parrilla y campana",
      "Recámara principal con clóset de piso a techo y espacio para pantalla",
      "Recámara con clóset y acceso a baño",
      "Baño completo con regadera de cristal y lavabo sobre cubierta",
      "Segundo baño completo con regadera de cristal",
      "Medio baño de visitas con lavabo sobre cubierta",
      "Escalera con tragaluz y barandal de acero",
      "Vestíbulo de acceso con vista al comedor y al jardín",
      "Recámara secundaria con ventanal e iluminación natural",
    ],
  },
  {
    id: "valle-de-zamarrero",
    title: "Refugio en la Laguna · Valle de Zamarrero",
    zone: "Toluca",
    location: "Valle de Zamarrero, Zinacantepec",
    type: "Casa",
    operation: "Venta",
    price: 12900000,
    beds: 4, baths: 4.5, parking: 4, built: 520, land: 1200,
    featured: true,
    tag: "Exclusiva",
    summary: "Residencia de lujo amueblada frente a la laguna, rodeada de bosque.",
    description: "Una residencia pensada para vivir la naturaleza sin renunciar al confort. Se entrega completamente amueblada, con chimenea central, terraza con vista a la laguna, estudio, bodega de vinos y amplios jardines dentro de un club residencial con campo de golf.",
    amenities: ["Amueblada", "Vista a la laguna", "Chimenea", "Club de golf", "Bodega de vinos", "Terraza"],
    images: [
      "img/propiedades/valle-de-zamarrero/01.webp",
      "img/propiedades/valle-de-zamarrero/02.webp",
      "img/propiedades/valle-de-zamarrero/03.webp",
      "img/propiedades/valle-de-zamarrero/04.webp",
      "img/propiedades/valle-de-zamarrero/05.webp",
      "img/propiedades/valle-de-zamarrero/06.webp",
      "img/propiedades/valle-de-zamarrero/07.webp",
      "img/propiedades/valle-de-zamarrero/08.webp",
      "img/propiedades/valle-de-zamarrero/09.webp",
      "img/propiedades/valle-de-zamarrero/10.webp",
      "img/propiedades/valle-de-zamarrero/11.webp",
      "img/propiedades/valle-de-zamarrero/12.webp",
      "img/propiedades/valle-de-zamarrero/13.webp",
      "img/propiedades/valle-de-zamarrero/14.webp",
      "img/propiedades/valle-de-zamarrero/15.webp",
      "img/propiedades/valle-de-zamarrero/16.webp",
      "img/propiedades/valle-de-zamarrero/17.webp",
      "img/propiedades/valle-de-zamarrero/18.webp",
    ],
    alts: [
      "Fachada principal de la residencia en Valle de Zamarrero, con jardín y palmeras",
      "Acceso principal con puerta de madera y jardinera",
      "Jardín amplio con árboles maduros alrededor de la casa",
      "Estancia principal con ventanales de piso a techo y vista al campo",
      "Sala luminosa con doble ventanal y salida al jardín",
      "Comedor formal con vista panorámica al jardín",
      "Antecomedor junto al ventanal con vista a la laguna y al campo",
      "Cocina con isla central, campana y barra de desayuno",
      "Cocina equipada con barra y bancos altos",
      "Estudio con biblioteca de piso a techo y escritorio",
      "Recámara principal amueblada con salida a la terraza",
      "Recámara con pantalla, escritorio y vista al jardín",
      "Vestidor amplio con clósets de madera",
      "Baño principal con doble lavabo y ventanal",
      "Baño con tina y acabados en mármol",
      "Ventanal con vista abierta al campo y al bosque",
      "Pasillo interior con muro de madera e iluminación natural",
      "Cochera techada con estructura de madera",
    ],
  },
  {
    id: "refugio-santa-fe",
    title: "Refugio Santa Fe",
    zone: "CDMX",
    location: "Santa Fe, Ciudad de México",
    type: "Departamento",
    operation: "Venta",
    price: 7350000,
    beds: 2, baths: 2, parking: 2, built: 128, land: null,
    featured: true,
    tag: "Destacado",
    summary: "Departamento con vista panorámica y amenidades de primer nivel.",
    description: "Departamento en piso alto con ventanales de piso a techo, iluminación natural todo el día y acceso a gimnasio, alberca techada, business center y seguridad las 24 horas. Ideal para vivir o invertir en renta ejecutiva.",
    amenities: ["Alberca techada", "Gimnasio", "Business center", "Seguridad 24/7", "Vista panorámica", "Elevador"],
    images: [
      "img/propiedades/refugio-santa-fe/01.webp",
      "img/propiedades/refugio-santa-fe/02.webp",
      "img/propiedades/refugio-santa-fe/03.webp",
      "img/propiedades/refugio-santa-fe/04.webp",
      "img/propiedades/refugio-santa-fe/05.webp",
      "img/propiedades/refugio-santa-fe/06.webp",
      "img/propiedades/refugio-santa-fe/07.webp",
      "img/propiedades/refugio-santa-fe/08.webp",
      "img/propiedades/refugio-santa-fe/09.webp",
      "img/propiedades/refugio-santa-fe/10.webp",
      "img/propiedades/refugio-santa-fe/11.webp",
      "img/propiedades/refugio-santa-fe/12.webp",
      "img/propiedades/refugio-santa-fe/13.webp",
      "img/propiedades/refugio-santa-fe/14.webp",
      "img/propiedades/refugio-santa-fe/15.webp",
      "img/propiedades/refugio-santa-fe/16.webp",
      "img/propiedades/refugio-santa-fe/17.webp",
      "img/propiedades/refugio-santa-fe/18.webp",
      "img/propiedades/refugio-santa-fe/19.webp",
      "img/propiedades/refugio-santa-fe/20.webp",
      "img/propiedades/refugio-santa-fe/21.webp",
      "img/propiedades/refugio-santa-fe/22.webp",
      "img/propiedades/refugio-santa-fe/23.webp",
      "img/propiedades/refugio-santa-fe/24.webp",
      "img/propiedades/refugio-santa-fe/25.webp",
      "img/propiedades/refugio-santa-fe/26.webp",
      "img/propiedades/refugio-santa-fe/27.webp",
      "img/propiedades/refugio-santa-fe/28.webp",
      "img/propiedades/refugio-santa-fe/29.webp",
      "img/propiedades/refugio-santa-fe/30.webp",
      "img/propiedades/refugio-santa-fe/31.webp",
      "img/propiedades/refugio-santa-fe/32.webp",
      "img/propiedades/refugio-santa-fe/33.webp",
      "img/propiedades/refugio-santa-fe/34.webp",
      "img/propiedades/refugio-santa-fe/35.webp",
      "img/propiedades/refugio-santa-fe/36.webp",
    ],
    alts: [
      "Fachada del desarrollo Refugio Santa Fe",
      "Acceso al edificio con escalera y muro de madera",
      "Pasillo de acceso con iluminación natural",
      "Corredor exterior con jardinera y muro verde",
      "Sala amueblada con ventanal y salida a la terraza",
      "Sala y comedor integrados en espacio abierto",
      "Sala con balcón y vista al exterior",
      "Estancia luminosa con ventanal de piso a techo",
      "Comedor amueblado para seis personas",
      "Comedor junto al ventanal con luz natural",
      "Cocina integral con cubierta de granito y campana",
      "Cocina equipada con parrilla y refrigerador",
      "Recámara principal amueblada con ventana amplia",
      "Recámara con clóset de madera de piso a techo",
      "Recámara con muro de madera y clóset integrado",
      "Recámara individual con cabecera acojinada",
      "Recámara con dos camas individuales y clóset",
      "Recámara con ventana y vista al exterior",
      "Recámara con clóset amplio junto a la ventana",
      "Baño principal con lavabo sobre cubierta y espejo amplio",
      "Baño con mueble de madera y cubierta de mármol",
      "Baño completo con regadera de cristal y lavabo",
      "Regadera con recubrimiento de mármol y cenefa decorativa",
      "Baño con regadera de cristal y WC",
      "Baño completo con regadera, WC y lavabo",
      "Segunda regadera de cristal con acabados en mármol",
      "Baño con lavabo sobre cubierta de madera",
      "Regadera de cristal templado en baño secundario",
      "Medio baño de visitas con espejo de cuerpo completo",
      "Baño con lavabo sobre cubierta de mármol y espejo",
      "Área de servicio con boiler y lavadero",
      "Cuarto de lavado con salida de servicios",
      "Terraza lateral con muro de madera",
      "Roof garden con barra de madera y asador",
      "Roof garden con comedor exterior y barandal de cristal",
      "Terraza en azotea con barra y área de asador",
    ],
  },
  {
    id: "cygnus-type-a",
    title: "Cygnus · Tipo A",
    zone: "Metepec",
    location: "Metepec, Estado de México",
    type: "Departamento",
    operation: "Venta",
    price: 3290000,
    beds: 2, baths: 2, parking: 1, built: 98, land: null,
    featured: false,
    tag: "Preventa",
    summary: "Preventa con plusvalía garantizada y amenidades tipo resort.",
    description: "Departamento en preventa dentro de una torre boutique con alberca, coworking, pet park y roof social. Diseño eficiente con terraza privada y excelente conectividad hacia Toluca y CDMX.",
    amenities: ["Alberca", "Coworking", "Pet park", "Roof social", "Terraza", "Preventa"],
    images: [IMG.apt2, IMG.living2, IMG.kitchen2, IMG.interior1],
  },
  {
    id: "cygnus-type-b",
    title: "Cygnus · Tipo B",
    zone: "Metepec",
    location: "Metepec, Estado de México",
    type: "Departamento",
    operation: "Venta",
    price: 3890000,
    beds: 3, baths: 2, parking: 2, built: 124, land: null,
    featured: false,
    tag: "Preventa",
    summary: "Tres recámaras con terraza amplia en torre boutique.",
    description: "La versión más amplia de Cygnus: tres recámaras, dos baños completos y una terraza pensada para reuniones. Acceso a todas las amenidades de la torre y dos cajones de estacionamiento.",
    amenities: ["3 recámaras", "Terraza amplia", "Alberca", "Coworking", "Gimnasio", "Preventa"],
    images: [IMG.apt3, IMG.interior2, IMG.kitchen1, IMG.living1],
  },
  {
    id: "arona-residencial",
    title: "Arona Residencial",
    zone: "Metepec",
    location: "San Salvador Tizatlalli, Metepec",
    type: "Casa",
    operation: "Venta",
    price: 5450000,
    beds: 3, baths: 3.5, parking: 2, built: 265, land: 200,
    featured: true,
    tag: "Destacado",
    summary: "Casa con jardín amplio dentro de privada con casa club.",
    description: "Casa moderna con recámara principal en planta baja, estudio, cocina abierta hacia el jardín y terraza techada. La privada cuenta con casa club, área de juegos y acceso controlado.",
    amenities: ["Casa club", "Recámara en PB", "Estudio", "Jardín", "Terraza techada", "Acceso controlado"],
    images: [IMG.house1, IMG.living2, IMG.kitchen2, IMG.interior1],
  },
  {
    id: "viena-residencial",
    title: "Viena Residencial",
    zone: "Toluca",
    location: "Toluca, Estado de México",
    type: "Casa",
    operation: "Venta",
    price: 3980000,
    beds: 3, baths: 2.5, parking: 2, built: 190, land: 140,
    featured: false,
    tag: null,
    summary: "Estilo clásico europeo en fraccionamiento consolidado.",
    description: "Residencia de dos niveles con fachada de inspiración europea, sala con chimenea, comedor independiente y patio de servicio. Excelente ubicación cerca de escuelas y centros comerciales.",
    amenities: ["Chimenea", "Comedor independiente", "Patio de servicio", "Vigilancia", "Áreas verdes"],
    images: [IMG.house2, IMG.living1, IMG.kitchen1, IMG.interior2],
  },
  {
    id: "la-escondida-residencial",
    title: "La Escondida Residencial",
    zone: "Metepec",
    location: "Metepec, Estado de México",
    type: "Casa",
    operation: "Venta",
    price: 6200000,
    beds: 4, baths: 4, parking: 3, built: 310, land: 260,
    featured: false,
    tag: null,
    summary: "Privacidad total en un rincón arbolado de Metepec.",
    description: "Casa de cuatro recámaras con estancia familiar, terraza con asador, jardín con árboles maduros y bodega. Desarrollo con pocas casas, ideal para familias que buscan tranquilidad.",
    amenities: ["Asador", "Árboles maduros", "Estancia familiar", "Bodega", "Pocas casas"],
    images: [IMG.house3, IMG.living2, IMG.kitchen2, IMG.interior1],
  },
  {
    id: "miranta-metepec",
    title: "Miranta Metepec",
    zone: "Metepec",
    location: "Metepec, Estado de México",
    type: "Casa",
    operation: "Venta",
    price: 4390000,
    beds: 3, baths: 2.5, parking: 2, built: 205, land: 160,
    featured: false,
    tag: null,
    summary: "Diseño funcional con acabados de lujo y excelente ubicación.",
    description: "Casa con acabados premium, pisos de porcelanato, cancelería de aluminio negro y cocina equipada. A pocos minutos de Paseo Tollocan y Av. Tecnológico.",
    amenities: ["Cocina equipada", "Porcelanato", "Cancelería premium", "Jardín", "Vigilancia"],
    images: [IMG.house4, IMG.interior2, IMG.kitchen1, IMG.living1],
  },
  {
    id: "residencial-terentia",
    title: "Residencial Terentia",
    zone: "Metepec",
    location: "Metepec, Estado de México",
    type: "Casa",
    operation: "Venta",
    price: 5790000,
    beds: 3, baths: 3.5, parking: 2, built: 250, land: 190,
    featured: false,
    tag: null,
    summary: "Casa con doble altura y roof garden en privada exclusiva.",
    description: "Espacios luminosos con doble altura en sala, family room en planta alta, vestidor en recámara principal y roof garden con medio baño. Privada con alberca y gimnasio.",
    amenities: ["Alberca", "Gimnasio", "Roof garden", "Vestidor", "Family room"],
    images: [IMG.modern3, IMG.living1, IMG.kitchen2, IMG.interior1],
  },
  {
    id: "residencial-la-providencia",
    title: "Residencial La Providencia",
    zone: "Metepec",
    location: "La Providencia, Metepec",
    type: "Casa",
    operation: "Venta",
    price: 3650000,
    beds: 3, baths: 2.5, parking: 2, built: 180, land: 130,
    featured: false,
    tag: null,
    summary: "Excelente opción familiar en zona de alta plusvalía.",
    description: "Casa lista para habitar con jardín, sala-comedor integrados y tres recámaras en planta alta. Fraccionamiento con parque, caseta de vigilancia y fácil acceso a escuelas.",
    amenities: ["Parque", "Caseta de vigilancia", "Jardín", "Lista para habitar"],
    images: [IMG.house5, IMG.living2, IMG.kitchen1, IMG.interior2],
  },
  {
    id: "hacienda-santa-maria",
    title: "Hacienda Santa María",
    zone: "Ixtlahuaca",
    location: "Santa María del Llano, Ixtlahuaca",
    type: "Terreno",
    operation: "Venta",
    price: 1850000,
    beds: null, baths: null, parking: null, built: null, land: 2500,
    featured: false,
    tag: "Inversión",
    summary: "Terreno campestre ideal para casa de descanso o proyecto productivo.",
    description: "Terreno plano con acceso pavimentado, servicios a pie de predio y vistas abiertas al valle. Perfecto para construir una casa de campo, un proyecto ecoturístico o como reserva patrimonial.",
    amenities: ["Terreno plano", "Acceso pavimentado", "Servicios a pie de predio", "Vista al valle"],
    images: [IMG.land, IMG.house6, IMG.villa],
  },
  {
    id: "rinconada-del-valle-temoaya",
    title: "Rinconada del Valle",
    zone: "Temoaya",
    location: "Temoaya, Estado de México",
    type: "Terreno",
    operation: "Venta",
    price: 980000,
    beds: null, baths: null, parking: null, built: null, land: 1000,
    featured: false,
    tag: "Inversión",
    summary: "Lotes campestres con escrituras y facilidades de pago.",
    description: "Lotes de 1,000 m² rodeados de bosque, con escritura individual y planes de financiamiento directo. Una inversión accesible con alta proyección de plusvalía.",
    amenities: ["Escrituras", "Financiamiento directo", "Entorno boscoso", "Acceso controlado"],
    images: [IMG.land, IMG.house6],
  },
  {
    id: "fraccionamiento-villas-del-campo",
    title: "Villas del Campo",
    zone: "Lerma",
    location: "Calimaya, Estado de México",
    type: "Casa",
    operation: "Renta",
    price: 18500,
    beds: 3, baths: 2.5, parking: 2, built: 160, land: 120,
    featured: true,
    tag: "Renta",
    summary: "Casa en renta dentro de fraccionamiento con amplias áreas verdes.",
    description: "Casa en excelentes condiciones con cocina integral, jardín, cuarto de lavado y tres recámaras. El fraccionamiento ofrece alberca, canchas y seguridad las 24 horas.",
    amenities: ["Alberca", "Canchas", "Seguridad 24/7", "Cocina integral", "Jardín"],
    images: [IMG.house6, IMG.living1, IMG.kitchen2, IMG.interior1],
  },
  {
    id: "departamento-en-renta-en-calle-moras",
    title: "Departamento en calle Moras",
    zone: "CDMX",
    location: "Colonia Acacias, Benito Juárez, CDMX",
    type: "Departamento",
    operation: "Renta",
    price: 26000,
    beds: 2, baths: 2, parking: 1, built: 95, land: null,
    featured: false,
    tag: "Renta",
    summary: "Departamento remodelado en la colonia Acacias, cerca de todo.",
    description: "Departamento completamente remodelado con cocina abierta, balcón y excelente iluminación. A pasos de parques, cafeterías y transporte en una de las colonias más cotizadas de Benito Juárez.",
    amenities: ["Remodelado", "Balcón", "Cocina abierta", "Elevador", "Pet friendly"],
    images: [IMG.apt2, IMG.living2, IMG.kitchen1, IMG.interior2],
  },
  {
    id: "oportunidad-de-inversion",
    title: "Nave industrial sobre avenida principal",
    zone: "Lerma",
    location: "Corredor industrial Lerma",
    type: "Comercial",
    operation: "Venta",
    price: 16500000,
    beds: null, baths: 2, parking: 10, built: 1200, land: 1800,
    featured: false,
    tag: "Inversión",
    summary: "Nave con oficinas y patio de maniobras en el corredor Toluca–Lerma.",
    description: "Nave industrial con altura libre de 9 m, oficinas en mezzanine, andén de carga, subestación eléctrica y patio de maniobras para tráileres. Frente a avenida principal con excelente visibilidad.",
    amenities: ["Altura 9 m", "Andén de carga", "Subestación", "Oficinas", "Patio de maniobras"],
    images: [IMG.office, IMG.forsale, IMG.meeting],
  },
];

const ZONES = [
  { name: "Metepec", img: IMG.modern2, text: "Plusvalía, seguridad y la mejor oferta residencial del Valle de Toluca." },
  { name: "Toluca", img: IMG.house2, text: "Conectividad, servicios y desarrollos consolidados." },
  { name: "CDMX", img: IMG.apt3, text: "Departamentos en las colonias más cotizadas de la ciudad." },
  { name: "Lerma", img: IMG.office, text: "Corredor industrial y casas en fraccionamientos con amenidades." },
  { name: "Ixtlahuaca", img: IMG.land, text: "Terrenos campestres con gran potencial de inversión." },
];

const POSTS = [
  {
    id: "plusvalia-metepec-2026",
    title: "¿Por qué Metepec sigue siendo la zona con mayor plusvalía del Valle de Toluca?",
    category: "Noticias",
    date: "2026-09-02",
    read: "5 min",
    cover: IMG.modern2,
    excerpt: "Analizamos los factores que mantienen a Metepec como el destino favorito para comprar casa: infraestructura, seguridad y nuevos desarrollos.",
    body: [
      "Metepec se ha consolidado como uno de los municipios más atractivos del Estado de México para vivir e invertir. En los últimos años, la llegada de nuevos centros comerciales, hospitales y la cercanía con el Tren Interurbano han impulsado la demanda de vivienda.",
      "## Infraestructura que impulsa el valor",
      "La conexión con la Ciudad de México a través del Tren Interurbano reduce los tiempos de traslado y abre la puerta a quienes trabajan en la capital pero buscan una mejor calidad de vida.",
      "## Oferta residencial en crecimiento",
      "Los desarrollos en privada con amenidades como casa club, alberca y seguridad 24/7 son los más buscados. Esto mantiene una demanda constante y precios al alza.",
      "## Nuestra recomendación",
      "Si estás pensando en comprar, el momento de preventa ofrece las mejores condiciones. Escríbenos y te mostramos las opciones que mejor se ajustan a tu presupuesto.",
    ],
  },
  {
    id: "reel-recorrido-grafito",
    title: "Reel: recorrido por Residencial Grafito I",
    category: "Reels",
    date: "2026-08-24",
    read: "1 min",
    cover: IMG.living1,
    video: "", // Pega aquí el enlace del reel (Instagram, TikTok o YouTube Shorts)
    excerpt: "Te llevamos dentro de una de nuestras casas más solicitadas en Metepec. Dobles alturas, roof garden y acabados impecables.",
    body: [
      "Recorre con nosotros Residencial Grafito I, una casa contemporánea de tres niveles en Metepec.",
      "Síguenos en redes sociales para ver nuevos recorridos cada semana.",
    ],
  },
  {
    id: "guia-credito-hipotecario",
    title: "Guía rápida: cómo elegir el crédito hipotecario ideal en 2026",
    category: "Guías",
    date: "2026-08-12",
    read: "7 min",
    cover: IMG.sign,
    excerpt: "Tasa fija, cofinanciamiento, Infonavit o banco: te explicamos en lenguaje claro qué conviene según tu perfil.",
    body: [
      "Elegir un crédito hipotecario es una de las decisiones financieras más importantes. Estos son los puntos que siempre revisamos con nuestros clientes.",
      "## 1. Compara el CAT, no solo la tasa",
      "El Costo Anual Total incluye comisiones y seguros. Es el mejor indicador para comparar entre bancos.",
      "## 2. Revisa tu capacidad de pago",
      "Lo recomendable es que la mensualidad no supere el 30% de tus ingresos comprobables.",
      "## 3. Aprovecha los esquemas de cofinanciamiento",
      "Combinar tu crédito Infonavit o Fovissste con un banco puede aumentar tu monto de compra.",
      "## Te acompañamos",
      "En Amábilis & Espinosa te conectamos con asesores hipotecarios y te ayudamos a integrar tu expediente sin costo adicional.",
    ],
  },
  {
    id: "reel-tips-home-staging",
    title: "Reel: 3 tips para vender tu casa más rápido",
    category: "Reels",
    date: "2026-07-30",
    read: "1 min",
    cover: IMG.interior2,
    video: "",
    excerpt: "Pequeños cambios que hacen una gran diferencia en fotos y visitas: iluminación, orden y neutralidad.",
    body: [
      "Preparar tu propiedad antes de publicarla puede reducir semanas el tiempo de venta.",
      "## Iluminación natural",
      "Abre cortinas y cambia focos por luz cálida. Las fotos se verán más amplias.",
      "## Menos es más",
      "Retira objetos personales para que el comprador se imagine viviendo ahí.",
    ],
  },
  {
    id: "invertir-terrenos-campestres",
    title: "Invertir en terrenos campestres: ventajas y lo que debes revisar",
    category: "Guías",
    date: "2026-07-15",
    read: "6 min",
    cover: IMG.land,
    excerpt: "Los terrenos en Ixtlahuaca y Temoaya ganan valor año con año. Esto es lo que debes verificar antes de comprar.",
    body: [
      "Los terrenos campestres son una alternativa de inversión patrimonial con bajo costo de mantenimiento y alto potencial de plusvalía.",
      "## Documentación en regla",
      "Verifica escrituras, uso de suelo y que el predio esté libre de gravámenes.",
      "## Acceso y servicios",
      "Un acceso pavimentado y servicios a pie de predio pueden duplicar el valor del terreno en pocos años.",
    ],
  },
  {
    id: "nom-247-derechos-consumidor",
    title: "NOM-247: conoce tus derechos al comprar una vivienda",
    category: "Noticias",
    date: "2026-06-28",
    read: "4 min",
    cover: IMG.keys,
    excerpt: "La norma que protege a los compradores de inmuebles en México. Te explicamos qué información deben darte siempre.",
    body: [
      "La NOM-247-SE-2021 establece la información y documentación que todo proveedor inmobiliario debe entregar al consumidor.",
      "## Información clara desde el inicio",
      "Precio total, formas de pago, características del inmueble y la carta de derechos del consumidor deben estar disponibles antes de firmar.",
      "## Nuestro compromiso",
      "En Amábilis & Espinosa cumplimos con la NOM-247 en cada operación para que compres con total tranquilidad.",
    ],
  },
];

/* ⚠️ PENDIENTE ANTES DE PUBLICAR: los textos y las fotos de abajo son de ejemplo.
   Las fotos (img/testimonios/ejemplo/) son de banco de imágenes, NO son clientes reales.
   Sustituye el texto y la ruta de photo por testimonios reales con autorización del cliente.
   Si dejas photo vacío (""), se muestra un círculo con las iniciales. */
const TESTIMONIALS = [
  { name: "Mariana G.", role: "Compró en Metepec", photo: "img/testimonios/ejemplo/ejemplo-1.jpg", text: "Nos acompañaron desde la primera visita hasta la entrega de llaves. Encontramos la casa perfecta en menos de un mes." },
  { name: "Ricardo S.", role: "Vendió su casa en Toluca", photo: "img/testimonios/ejemplo/ejemplo-3.jpg", text: "Vendieron mi propiedad en tiempo récord y al precio que buscaba. Muy profesionales y siempre disponibles." },
  { name: "Familia Ortega", role: "Rentó en CDMX", photo: "img/testimonios/ejemplo/ejemplo-2.jpg", text: "Transparencia total en cada paso. Se nota la experiencia y el cuidado que ponen en cada cliente." },
];

/* =========================================================
   Contenido en inglés
   Solo se escriben los campos que cambian; los demás se toman del español.
   ========================================================= */
const EN_CONTENT = {
  properties: {
    "residencial-grafito-i": {
      location: "Metepec, State of Mexico",
      summary: "Contemporary architecture in one of Metepec's most sought-after developments.",
      description: "Three-story home with double-height ceilings, an integrated kitchen with island, private roof garden, and wood and natural stone finishes. Located in a gated community with 24/7 security, minutes from Galerías Metepec and major roads.",
      amenities: ["Roof garden", "24/7 security", "Kitchen island", "Double-height ceilings", "Staff quarters", "Private garden"],
      alts: [
        "Facade of Residencial Grafito I in Metepec, with front garden and private entrance",
        "Living room with TV, garden-facing window and double-height ceiling",
        "Open living and dining area with staircase to the upper floor",
        "Dining room with a large window facing the garden",
        "Fitted kitchen with island, cooktop and range hood",
        "Primary bedroom with floor-to-ceiling closet and space for a TV",
        "Bedroom with closet and access to the bathroom",
        "Full bathroom with glass shower and vessel sink",
        "Second full bathroom with glass shower",
        "Guest half bathroom with vessel sink",
        "Staircase with skylight and steel railing",
        "Entry hall with a view of the dining room and garden",
        "Second bedroom with large window and natural light",
      ],
    },
    "valle-de-zamarrero": {
      title: "Lakeside Retreat · Valle de Zamarrero",
      location: "Valle de Zamarrero, Zinacantepec",
      summary: "Fully furnished luxury residence on the lake, surrounded by forest.",
      description: "A residence designed to enjoy nature without giving up comfort. Delivered fully furnished, with a central fireplace, a terrace overlooking the lake, a study, a wine cellar and large gardens within a residential club with a golf course.",
      amenities: ["Furnished", "Lake view", "Fireplace", "Golf club", "Wine cellar", "Terrace"],
      alts: [
        "Main facade of the residence in Valle de Zamarrero, with garden and palm trees",
        "Main entrance with wooden door and planter",
        "Large garden with mature trees around the house",
        "Main living room with floor-to-ceiling windows and countryside views",
        "Bright living room with double windows opening to the garden",
        "Formal dining room with panoramic garden views",
        "Breakfast area by the window with views of the lake and countryside",
        "Kitchen with central island, range hood and breakfast bar",
        "Fully equipped kitchen with bar and high stools",
        "Study with floor-to-ceiling bookshelves and desk",
        "Furnished primary bedroom with access to the terrace",
        "Bedroom with TV, desk and garden view",
        "Spacious walk-in closet with wooden wardrobes",
        "Primary bathroom with double vanity and large window",
        "Bathroom with bathtub and marble finishes",
        "Picture window with open views of the countryside and forest",
        "Interior hallway with wood-panelled wall and natural light",
        "Covered carport with wooden structure",
      ],
    },
    "refugio-santa-fe": {
      location: "Santa Fe, Mexico City",
      summary: "Apartment with panoramic views and first-class amenities.",
      description: "High-floor apartment with floor-to-ceiling windows, natural light all day, and access to a gym, indoor pool, business center and 24-hour security. Ideal to live in or to invest in as an executive rental.",
      amenities: ["Indoor pool", "Gym", "Business center", "24/7 security", "Panoramic view", "Elevator"],
      alts: [
        "Facade of the Refugio Santa Fe development",
        "Building entrance with staircase and wood-clad wall",
        "Entrance corridor with natural light",
        "Outdoor corridor with planter and green wall",
        "Furnished living room with large window and terrace access",
        "Open-plan living and dining area",
        "Living room with balcony and outdoor view",
        "Bright living area with floor-to-ceiling window",
        "Dining room furnished for six",
        "Dining room next to the window with natural light",
        "Fitted kitchen with granite countertop and range hood",
        "Equipped kitchen with cooktop and refrigerator",
        "Furnished primary bedroom with large window",
        "Bedroom with floor-to-ceiling wooden closet",
        "Bedroom with wood-panelled wall and built-in closet",
        "Single bedroom with upholstered headboard",
        "Bedroom with two single beds and closet",
        "Bedroom with window and outdoor view",
        "Bedroom with spacious closet beside the window",
        "Primary bathroom with vessel sink and large mirror",
        "Bathroom with wooden vanity and marble countertop",
        "Full bathroom with glass shower and sink",
        "Shower with marble cladding and decorative trim",
        "Bathroom with glass shower and toilet",
        "Full bathroom with shower, toilet and sink",
        "Second glass shower with marble finishes",
        "Bathroom with sink on a wooden countertop",
        "Tempered glass shower in the secondary bathroom",
        "Guest half bathroom with full-length mirror",
        "Bathroom with marble countertop sink and mirror",
        "Utility area with water heater and laundry sink",
        "Laundry room with utility connections",
        "Side terrace with wood-clad wall",
        "Roof garden with wooden bar and grill",
        "Roof garden with outdoor dining and glass railing",
        "Rooftop terrace with bar and grill area",
      ],
    },
    "cygnus-type-a": {
      title: "Cygnus · Type A",
      location: "Metepec, State of Mexico",
      summary: "Pre-sale unit with strong appreciation and resort-style amenities.",
      description: "Pre-sale apartment in a boutique tower with a pool, coworking space, pet park and social rooftop. Efficient layout with a private terrace and excellent access to Toluca and Mexico City.",
      amenities: ["Pool", "Coworking", "Pet park", "Social rooftop", "Terrace", "Pre-sale"],
    },
    "cygnus-type-b": {
      title: "Cygnus · Type B",
      location: "Metepec, State of Mexico",
      summary: "Three bedrooms with a large terrace in a boutique tower.",
      description: "The most spacious Cygnus layout: three bedrooms, two full bathrooms and a terrace designed for entertaining. Access to all tower amenities and two parking spaces.",
      amenities: ["3 bedrooms", "Large terrace", "Pool", "Coworking", "Gym", "Pre-sale"],
    },
    "arona-residencial": {
      location: "San Salvador Tizatlalli, Metepec",
      summary: "Home with a large garden in a gated community with clubhouse.",
      description: "Modern home with a ground-floor primary bedroom, study, open kitchen facing the garden and covered terrace. The community features a clubhouse, playground and controlled access.",
      amenities: ["Clubhouse", "Ground-floor bedroom", "Study", "Garden", "Covered terrace", "Controlled access"],
    },
    "viena-residencial": {
      location: "Toluca, State of Mexico",
      summary: "Classic European style in an established neighborhood.",
      description: "Two-story home with a European-inspired façade, living room with fireplace, separate dining room and service patio. Excellent location near schools and shopping centers.",
      amenities: ["Fireplace", "Separate dining room", "Service patio", "Security", "Green areas"],
    },
    "la-escondida-residencial": {
      location: "Metepec, State of Mexico",
      summary: "Complete privacy in a tree-lined corner of Metepec.",
      description: "Four-bedroom home with family room, terrace with grill, garden with mature trees and storage room. A small development, ideal for families seeking tranquility.",
      amenities: ["Grill", "Mature trees", "Family room", "Storage", "Few homes"],
    },
    "miranta-metepec": {
      location: "Metepec, State of Mexico",
      summary: "Functional design with luxury finishes and a great location.",
      description: "Home with premium finishes, porcelain floors, black aluminum window frames and a fully equipped kitchen. Just minutes from Paseo Tollocan and Av. Tecnológico.",
      amenities: ["Equipped kitchen", "Porcelain floors", "Premium windows", "Garden", "Security"],
    },
    "residencial-terentia": {
      location: "Metepec, State of Mexico",
      summary: "Home with double-height ceilings and roof garden in an exclusive community.",
      description: "Bright spaces with a double-height living room, upstairs family room, walk-in closet in the primary bedroom and a roof garden with half bath. The community has a pool and gym.",
      amenities: ["Pool", "Gym", "Roof garden", "Walk-in closet", "Family room"],
    },
    "residencial-la-providencia": {
      location: "La Providencia, Metepec",
      summary: "A great family option in a high-appreciation area.",
      description: "Move-in ready home with garden, open living and dining area and three upstairs bedrooms. The neighborhood has a park, guard house and easy access to schools.",
      amenities: ["Park", "Guard house", "Garden", "Move-in ready"],
    },
    "hacienda-santa-maria": {
      summary: "Countryside land ideal for a weekend home or productive project.",
      description: "Flat lot with paved access, utilities at the lot line and open views of the valley. Perfect for building a country home, an eco-tourism project or as a long-term asset.",
      amenities: ["Flat lot", "Paved access", "Utilities available", "Valley view"],
    },
    "rinconada-del-valle-temoaya": {
      location: "Temoaya, State of Mexico",
      summary: "Countryside lots with title deeds and flexible payment plans.",
      description: "1,000 m² lots surrounded by forest, each with an individual title deed and direct financing plans. An accessible investment with strong appreciation potential.",
      amenities: ["Title deeds", "Direct financing", "Forest setting", "Controlled access"],
    },
    "fraccionamiento-villas-del-campo": {
      location: "Calimaya, State of Mexico",
      summary: "House for rent in a community with large green areas.",
      description: "Home in excellent condition with a fitted kitchen, garden, laundry room and three bedrooms. The community offers a pool, sports courts and 24-hour security.",
      amenities: ["Pool", "Sports courts", "24/7 security", "Fitted kitchen", "Garden"],
    },
    "departamento-en-renta-en-calle-moras": {
      title: "Apartment on Moras Street",
      location: "Colonia Acacias, Benito Juárez, Mexico City",
      summary: "Renovated apartment in Colonia Acacias, close to everything.",
      description: "Fully renovated apartment with an open kitchen, balcony and excellent natural light. Steps from parks, cafés and public transit in one of Benito Juárez's most desirable neighborhoods.",
      amenities: ["Renovated", "Balcony", "Open kitchen", "Elevator", "Pet friendly"],
    },
    "oportunidad-de-inversion": {
      title: "Industrial warehouse on a main avenue",
      location: "Lerma industrial corridor",
      summary: "Warehouse with offices and truck yard in the Toluca–Lerma corridor.",
      description: "Industrial warehouse with 9 m clear height, mezzanine offices, loading dock, electrical substation and a maneuvering yard for trailers. Main-avenue frontage with excellent visibility.",
      amenities: ["9 m clear height", "Loading dock", "Substation", "Offices", "Truck yard"],
    },
  },
  zones: {
    Metepec: "Appreciation, safety and the best residential offering in the Toluca Valley.",
    Toluca: "Connectivity, services and established developments.",
    CDMX: "Apartments in the city's most sought-after neighborhoods.",
    Lerma: "Industrial corridor and homes in communities with amenities.",
    Ixtlahuaca: "Countryside land with great investment potential.",
  },
  posts: {
    "plusvalia-metepec-2026": {
      title: "Why is Metepec still the highest-appreciation area in the Toluca Valley?",
      excerpt: "We analyze the factors that keep Metepec the favorite place to buy a home: infrastructure, safety and new developments.",
      body: [
        "Metepec has become one of the most attractive municipalities in the State of Mexico to live and invest. In recent years, new shopping centers, hospitals and proximity to the Interurban Train have driven housing demand.",
        "## Infrastructure that drives value",
        "The connection to Mexico City via the Interurban Train shortens commute times and opens the door to people who work in the capital but want a better quality of life.",
        "## Growing residential supply",
        "Gated developments with amenities such as a clubhouse, pool and 24/7 security are the most in demand. This keeps demand steady and prices rising.",
        "## Our recommendation",
        "If you are thinking about buying, the pre-sale stage offers the best terms. Message us and we'll show you the options that best fit your budget.",
      ],
    },
    "reel-recorrido-grafito": {
      title: "Reel: a tour of Residencial Grafito I",
      excerpt: "Step inside one of our most requested homes in Metepec. Double-height ceilings, a roof garden and flawless finishes.",
      body: [
        "Tour Residencial Grafito I with us, a contemporary three-story home in Metepec.",
        "Follow us on social media for new tours every week.",
      ],
    },
    "guia-credito-hipotecario": {
      title: "Quick guide: how to choose the right mortgage in 2026",
      excerpt: "Fixed rate, co-financing, Infonavit or bank: we explain in plain language what works best for your profile.",
      body: [
        "Choosing a mortgage is one of the most important financial decisions you will make. These are the points we always review with our clients.",
        "## 1. Compare the CAT, not just the rate",
        "The Total Annual Cost (CAT) includes fees and insurance. It is the best indicator for comparing banks.",
        "## 2. Check your repayment capacity",
        "Ideally, your monthly payment should not exceed 30% of your verifiable income.",
        "## 3. Take advantage of co-financing",
        "Combining your Infonavit or Fovissste credit with a bank loan can increase your purchase amount.",
        "## We're here to help",
        "At Amábilis & Espinosa we connect you with mortgage advisors and help you put together your application at no extra cost.",
      ],
    },
    "reel-tips-home-staging": {
      title: "Reel: 3 tips to sell your home faster",
      excerpt: "Small changes that make a big difference in photos and viewings: lighting, tidiness and neutral spaces.",
      body: [
        "Preparing your property before listing it can cut weeks off the time it takes to sell.",
        "## Natural light",
        "Open the curtains and switch to warm light bulbs. Your photos will look more spacious.",
        "## Less is more",
        "Remove personal items so buyers can picture themselves living there.",
      ],
    },
    "invertir-terrenos-campestres": {
      title: "Investing in countryside land: benefits and what to check",
      excerpt: "Land in Ixtlahuaca and Temoaya gains value every year. Here's what you should verify before buying.",
      body: [
        "Countryside land is a long-term investment alternative with low maintenance costs and high appreciation potential.",
        "## Paperwork in order",
        "Verify the title deed, land use and that the lot is free of liens.",
        "## Access and utilities",
        "Paved access and utilities at the lot line can double the value of the land within a few years.",
      ],
    },
    "nom-247-derechos-consumidor": {
      title: "NOM-247: know your rights when buying a home",
      excerpt: "The standard that protects property buyers in Mexico. We explain what information you must always receive.",
      body: [
        "NOM-247-SE-2021 establishes the information and documentation every real estate provider must give the consumer.",
        "## Clear information from the start",
        "Total price, payment methods, property details and the consumer rights charter must be available before signing.",
        "## Our commitment",
        "At Amábilis & Espinosa we comply with NOM-247 in every transaction so you can buy with complete peace of mind.",
      ],
    },
  },
  testimonials: [
    { role: "Bought in Metepec", text: "They guided us from the first viewing to the key handover. We found the perfect home in less than a month." },
    { role: "Sold his home in Toluca", text: "They sold my property in record time and at the price I wanted. Very professional and always available." },
    { role: "Rented in Mexico City", text: "Complete transparency at every step. You can tell the experience and care they put into every client." },
  ],
};

const LANG = (window.I18N && window.I18N.lang) || "es";
if (LANG === "en") {
  PROPERTIES.forEach((p) => Object.assign(p, EN_CONTENT.properties[p.id] || {}));
  POSTS.forEach((p) => Object.assign(p, EN_CONTENT.posts[p.id] || {}));
  ZONES.forEach((z) => { if (EN_CONTENT.zones[z.name]) z.text = EN_CONTENT.zones[z.name]; });
  TESTIMONIALS.forEach((t, i) => Object.assign(t, EN_CONTENT.testimonials[i] || {}));
}

/* Helpers */
const fmtPrice = (p) =>
  p.operation === "Renta"
    ? `$${p.price.toLocaleString("es-MX")} <small>${LANG === "en" ? "MXN / month" : "MXN / mes"}</small>`
    : `$${p.price.toLocaleString("es-MX")} <small>MXN</small>`;

const fmtDate = (d) =>
  new Date(d + "T12:00:00").toLocaleDateString(LANG === "en" ? "en-US" : "es-MX", { day: "numeric", month: "long", year: "numeric" });

const waLink = (msg) =>
  `https://wa.me/${SITE.whatsapp}?text=${encodeURIComponent(msg || (LANG === "en"
    ? "Hi, I'd like to receive information about your properties."
    : "Hola, me interesa recibir información de sus propiedades."))}`;
